<?php
session_start();
?>
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Stepcone 2023</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <!-- Icon -->
    <link rel="shortcut icon" href="./images/favicon_transp.png" type="image/x-icon">
	<!-- CSS here -->
	<link rel="stylesheet" href="./assets/css/bootstrap.min.css">
	<link rel="stylesheet" href="./assets/css/owl.carousel.min.css">
	<link rel="stylesheet" href="./assets/css/slicknav.css">
    <!-- <link rel="stylesheet" href="./assets/css/flaticon.css">
    <link rel="stylesheet" href="./assets/css/gijgo.css"> -->
	<link rel="stylesheet" href="./assets/css/animate.min.css">
	<!-- <link rel="stylesheet" href="./assets/css/magnific-popup.css"> -->
	<link rel="stylesheet" href="./assets/css/fontawesome-all.min.css">
	<link rel="stylesheet" href="./assets/css/themify-icons.css">
	<link rel="stylesheet" href="./assets/css/slick.css">
	<!-- <link rel="stylesheet" href="./assets/css/nice-select.css"> -->
	<link rel="stylesheet" href="./assets/css/style.css">

    <link rel="stylesheet" href="./events/event.css">
    <link rel="stylesheet" href="./events/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.js"></script>
    <script src="./events/js/bootstrap.min.js"></script>
    <style>
        .event-title {
            padding-top: 35vh;
            padding-bottom: 35vh;
            background: url("./events/image/idp.jpeg") no-repeat;
            opacity: 0.8;
            background-size: cover;
            background-position: center;
            background-attachment: fixed;
            position: relative;
            z-index: 1;
        }
        .event-title .t p
        {
            font-size: 4rem;
            text-align: center;
            padding: 20px;
            text-transform: uppercase;
            font-size: 600;
            color:aliceblue
        }
        .event-title:before {
            content: "";
            position: absolute;
            box-sizing: border-box;
            left: 0;
            top: 0;
            right: 0;
            bottom: 0;
            background-color: black;
            opacity: 0.4;
            z-index: -1;
        }
        .person .profile a{
            color:#000;
        }
        .person .profile a: hover{
            color:#fff;
        }
    </style>
    <script>
        $(window).scroll(function () {
            if ($(this).scrollTop() > 400) {
                $('.chevron').fadeOut(200);
            } else {
                $('.chevron').fadeIn(200);
            }
        });
    </script>
</head>
<body>
    
    <?php
    include './header.php';
    ?>

    <div class="row event-title">
        <div class="col-2"></div>
        <div class="col-8 t" data-aos="zoom-out" data-aos-duration="2000">
            <p>Industrial Defined Problem</p>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="container">
        <div class="chevron"></div>
        <div class="chevron"></div>
        <div class="chevron"></div>
    </div>
    <div class="row event" data-aos="fade-right">
        <h2>Industrial Defined Problem</h2>
    </div>
    <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 content" data-aos="fade-right" align="justify">
        <p>Do you want to prove your thinking ability or do you want to challenge the conventional thinking. Then what are you waiting for. Here is the chance to showcase your thinking ability. IDP (Industry Defined Problem) is an event that meet all your requirements and goals of industries. Actually, the main agenda of any company is to produce a product at minimum price with high quality. In this regard they come up with a problem regarding their needs and requirements. Now in this event the participants are given with those problem statements that are taken from the industries and the solutions are to be generated by an idea in keeping all the constraints of problem in the mind. 
New problem, new solution…. Then what are you waiting for. Come on ..join us in the event and put the solutions for day to day engineers life.</p>
        <div class="buttons" data-aos="fade-up">
                <a href="./eventRegistration.php?event=333"> <button>register</button></a>
                <a href="#"><button>download pdf</button></a>
            </div>
        </div>
        <div class="col-lg-5 col-md-12 col-sm-12 tools">
            <div class="box" data-aos="fade-right" data-aos-duration="1000">
                <div class="text">prize money:<br>winner-Rs 7,500/-</div>
            </div>
            <div class="box" data-aos="fade-right" data-aos-duration="1000">
                <div class="text">team size:<br>1-3 members</div>
            </div>
            <div class="box" data-aos="fade-right" data-aos-duration="1000">
                <div class="text">registration fee:<br>Rs 500/-</div>
            </div>
        </div>
       
        <div class="row person">
        <div class="co">FACULTY COORDINATORS</div>
            <div class="col-lg-3 col-md-6 col-sm-4 profile" data-aos="zoom-in" style="width:auto">
                <img src="./events/image/men.png" alt="">Dr. B. Anil Kumar <br>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-4 profile" data-aos="zoom-in" style="width:auto">
                <img src="./events/image/men.png" alt="">Mr. M. Hari Krishna<br>
            </div>
        </div>
      
        <div class="row person">
        <div class="co">COORDINATORS</div>
            <div class="col-lg-3 col-md-6 col-sm-4 profile" data-aos="zoom-in" style="width:auto">
                <img src="./events/image/men.png" alt="">B. V. Sai Koushik<br><a href="tel:8639028134">8639028134</a>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-4 profile" data-aos="zoom-in" style="width:auto">
                <img src="./events/image/men.png" alt="">A. Vandana &nbsp&nbsp<br><a href="tel:9347264757">9347264757</a>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-4 profile" data-aos="zoom-in" style="width:auto">
                <img src="./events/image/men.png" alt="">K. Deepika &nbsp&nbsp<br><a href="tel:6309416726">6309416726</a>
            </div>
        </div>
    </div>
    <br><br>/
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script>
        AOS.init();
    </script>
    
    


     <!-- JS here -->

     <script src="../assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="../assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="../assets/js/popper.min.js"></script>
    <script src="../assets/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="../assets/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="../assets/js/owl.carousel.min.js"></script>
    <script src="../assets/js/slick.min.js"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="../assets/js/wow.min.js"></script>
    <script src="../assets/js/animated.headline.js"></script>
    <script src="../assets/js/jquery.magnific-popup.js"></script>

    <!-- Date Picker -->
    <script src="../assets/js/gijgo.min.js"></script>
    <!-- Nice-select, sticky -->
    <script src="../assets/js/jquery.nice-select.min.js"></script>
    <script src="../assets/js/jquery.sticky.js"></script>
    
    <!-- counter , waypoint -->
    <script src="../assets/js/jquery.counterup.min.js"></script>
    <script src="../assets/js/waypoints.min.js"></script>
    <script src="../assets/js/jquery.countdown.min.js"></script>
    <!-- contact js -->
    <script src="../assets/js/contact.js"></script>
    <script src="../assets/js/jquery.form.js"></script>
    <script src="../assets/js/jquery.validate.min.js"></script>
    <script src="../assets/js/mail-script.js"></script>
    <script src="../assets/js/jquery.ajaxchimp.min.js"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    <script src="../assets/js/plugins.js"></script>
    <script src="../assets/js/main.js"></script>
   
    </body>
</html>